name: 🚀 Build and publish Docker image

on:
  push:
    tags:
      - 'moc-*'
      - 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          export DOCKER_BUILDKIT=1
          docker compose build \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from=type=registry,ref=ghcr.io/research-ag/motoko-build:cache \
            --cache-to=type=registry,ref=ghcr.io/research-ag/motoko-build:cache,mode=max base

      - name: Push Docker image
        run: docker push "ghcr.io/research-ag/motoko-build:${{ github.ref_name }}"
