name: 🚀 Build the Wasm module and compute module hash

on:
  push:
    tags:
      - 'build-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Wasm module
        run: docker compose run --rm wasm

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: out/out_Linux_x86_64.wasm*